services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env  
    environment:
      - PORT=3000
    networks:
      - riftscope-net
    expose:
      - "3000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - riftscope-net

  redis:
    image: redis:alpine
    networks:
      - riftscope-net

networks:
  riftscope-net:
    driver: bridge